import { app, BrowserWindow } from 'electron';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
export let mainWindow: BrowserWindow | null = null;
const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 1024,
    width: 1024,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

export let ideArg: string = null // default to localhost:8080
export let folderArg: string = null // default to os.homedir()

// load the flags --folder and --remix-ide-url
const args = process.argv.slice(1)
const url = args.find(arg => arg.startsWith('--remix-ide-url='))
if (url) {
  ideArg = url.split('=')[1]
}
const argsFolder = args.find(arg => arg.startsWith('--folder='))
if (argsFolder) {
  folderArg = argsFolder.split('=')[1]
}
export const isE2E = args.find(arg => arg.startsWith('--e2e'))
if (isE2E) {
  console.log('e2e mode')
}

console.log('ideArg', ideArg)
console.log('folderArg', folderArg)




// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});


require('./remixd')
