name: remix-publish-action
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.0.0
      - run: yarn install
      - run: ls
      - run: pwd
      - run: yarn run build:production
      - run: echo "action_state=$('./apps/remix-ide/ci/publishIpfs' ${{ secrets.IPFS_PROJET_ID }} ${{ secrets.IPFS_PROJECT_SECRET }})" >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ipfs://${{ env.action_state }}
            https://remix-project.infura-ipfs.io/ipfs/${{ env.action_state }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

